export { useGetProducts, useGetProductById, productKeys } from "./queries/products"
export { useGetOrders, useGetOrderById, orderKeys } from "./queries/orders"
export { useGetDashboardStats, useGetRevenueData, useGetCategoryData, dashboardKeys } from "./queries/dashboard"
export { useGetCustomers, useGetCustomerById, customerKeys } from "./queries/customers"
export { useGetCategories, useGetCategoryById, categoryKeys } from "./queries/categories"

export { useCreateProduct, useUpdateProduct, useDeleteProduct } from "./mutations/products"
export { useUpdateOrderStatus } from "./mutations/orders"
export { useCreateCustomer, useUpdateCustomer, useUpdateCustomerStatus, useDeleteCustomer } from "./mutations/customers"
export { useCreateCategory, useUpdateCategory, useUpdateCategoryStatus, useDeleteCategory } from "./mutations/categories"
